const PDFDocument = require('pdfkit');
const { getLabResults, getDoseLogs, getWellnessLogs, getCurrentStreak } = require('./db.js');

const NAVY = '#0A1628';
const WHITE = '#0A1628';
const MUTED = '#64748B';
const BLUE = '#3B82F6';
const RED = '#EF4444';
const GREEN = '#10B981';
const AMBER = '#F59E0B';

const REF = { tsh: [0.35, 4.94], ft3: [2.43, 6.02], ft4: [9.0, 19.0] };

function footer(doc) {
  // Written comfortably above the page's bottom margin (not right at the
  // edge) — pdfkit silently auto-inserts a blank extra page if a text call
  // would overflow the printable area, which a footer sitting exactly on
  // the margin boundary reliably triggers.
  const bottom = doc.page.height - 55;
  doc
    .fontSize(7)
    .fillColor(MUTED)
    .text(
      'Generated by ThyroTrack — for informational purposes only. Not a substitute for medical advice.',
      40,
      bottom,
      { width: doc.page.width - 80, align: 'center', lineBreak: false }
    );
}

function outOfRange(value, [low, high]) {
  return value != null && (value < low || value > high);
}

function pageHeader(doc, title) {
  doc.fontSize(9).fillColor(BLUE).text('THYROTRACK', 40, 40);
  doc.fontSize(16).fillColor(WHITE).text(title, 40, 56);
  doc.moveTo(40, 84).lineTo(doc.page.width - 40, 84).strokeColor('#E2E8F0').stroke();
  doc.y = 100;
}

function monthKey(dateStr) {
  return (dateStr || '').slice(0, 7);
}

function formatMonth(key) {
  const [y, m] = key.split('-');
  const names = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
  return `${names[Number(m) - 1]} ${y}`;
}

function generateDoctorReportPdf({ name, patientId, status, dose }, res) {
  const doc = new PDFDocument({ size: 'A4', margin: 40, bufferPages: true });
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', 'attachment; filename="thyrotrack-doctor-report.pdf"');
  doc.pipe(res);

  const results = getLabResults(1000);
  const doseLogs = getDoseLogs(2000);
  const wellnessLogs = getWellnessLogs(1000);

  // ---------- Page 1: Patient summary ----------
  pageHeader(doc, 'Patient Summary');
  doc.fontSize(11).fillColor(WHITE);
  const rows1 = [
    ['Patient name', name || 'Not provided'],
    ['Patient ID', patientId || 'Not provided'],
    ['Thyroid status', status || 'Not provided'],
    ['Current dose', dose ? `${dose} mcg levothyroxine` : 'Not provided'],
    ['Report generated', new Date().toLocaleDateString('en-GB', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })],
    ['Total lab results on file', String(results.length)],
    ['Current medication streak', `${getCurrentStreak(new Date().toISOString().slice(0, 10))} days`],
  ];
  let y = doc.y + 10;
  rows1.forEach(([label, value]) => {
    doc.fontSize(9).fillColor(MUTED).text(label, 40, y, { continued: false });
    doc.fontSize(11).fillColor(WHITE).text(value, 220, y);
    y += 26;
  });
  footer(doc);

  // ---------- Page 2: Lab results history table ----------
  doc.addPage();
  pageHeader(doc, 'Lab Results History');

  if (results.length === 0) {
    doc.fontSize(10).fillColor(MUTED).text('No lab results have been recorded yet.', 40, doc.y + 10);
  } else {
    const cols = [
      { key: 'date', label: 'Date', w: 75 },
      { key: 'tsh', label: 'TSH', w: 65 },
      { key: 'ft3', label: 'Free T3', w: 65 },
      { key: 'ft4', label: 'Free T4', w: 65 },
      { key: 'dose', label: 'Dose', w: 65 },
      { key: 'dx', label: 'State', w: 130 },
    ];
    let tableY = doc.y + 6;
    let x = 40;
    doc.fontSize(8).fillColor(MUTED);
    cols.forEach((c) => { doc.text(c.label, x, tableY, { width: c.w }); x += c.w; });
    tableY += 16;
    doc.moveTo(40, tableY).lineTo(505, tableY).strokeColor('#E2E8F0').stroke();
    tableY += 6;

    results.forEach((r) => {
      if (tableY > doc.page.height - 80) {
        footer(doc);
        doc.addPage();
        pageHeader(doc, 'Lab Results History (continued)');
        tableY = doc.y + 6;
      }
      x = 40;
      const cells = {
        date: r.date,
        tsh: r.tsh != null ? String(r.tsh) : '—',
        ft3: r.ft3 != null ? String(r.ft3) : '—',
        ft4: r.ft4 != null ? String(r.ft4) : '—',
        dose: r.dose != null ? `${r.dose}mcg` : '—',
        dx: (r.dx || '').replace(/_/g, ' ') || '—',
      };
      cols.forEach((c) => {
        const flagged = (c.key === 'tsh' && outOfRange(r.tsh, REF.tsh)) ||
          (c.key === 'ft3' && outOfRange(r.ft3, REF.ft3)) ||
          (c.key === 'ft4' && outOfRange(r.ft4, REF.ft4));
        doc.fontSize(9).fillColor(flagged ? RED : WHITE).text(cells[c.key], x, tableY, { width: c.w });
        x += c.w;
      });
      tableY += 18;
    });
  }
  footer(doc);

  // ---------- Page 3: TSH trend chart ----------
  doc.addPage();
  pageHeader(doc, 'TSH Trend');

  const chartX = 50;
  const chartY = doc.y + 20;
  const chartW = 470;
  const chartH = 260;
  const tshVals = results.filter((r) => r.tsh != null);

  doc.rect(chartX, chartY, chartW, chartH).strokeColor('#E2E8F0').stroke();

  if (tshVals.length > 0) {
    const allVals = tshVals.map((r) => r.tsh);
    const maxV = Math.max(...allVals, REF.tsh[1]) * 1.15;
    const minV = Math.min(0, Math.min(...allVals) * 0.9);
    const scaleY = (v) => chartY + chartH - ((v - minV) / (maxV - minV)) * chartH;
    const scaleX = (i) => chartX + (tshVals.length === 1 ? chartW / 2 : (i / (tshVals.length - 1)) * chartW);

    // Reference range band (shaded)
    const bandTop = scaleY(REF.tsh[1]);
    const bandBottom = scaleY(REF.tsh[0]);
    doc.rect(chartX, bandTop, chartW, bandBottom - bandTop).fillOpacity(0.12).fill(GREEN).fillOpacity(1);

    // Line
    doc.strokeColor(BLUE).lineWidth(1.5);
    tshVals.forEach((r, i) => {
      const px = scaleX(i);
      const py = scaleY(r.tsh);
      if (i === 0) doc.moveTo(px, py);
      else doc.lineTo(px, py);
    });
    doc.stroke();

    // Points + dose-change markers
    let lastDose = null;
    tshVals.forEach((r, i) => {
      const px = scaleX(i);
      const py = scaleY(r.tsh);
      doc.circle(px, py, 3).fillColor(outOfRange(r.tsh, REF.tsh) ? RED : BLUE).fill();
      if (lastDose != null && r.dose != null && r.dose !== lastDose) {
        doc.strokeColor(AMBER).lineWidth(1).moveTo(px, chartY).lineTo(px, chartY + chartH).dash(3, { space: 2 }).stroke().undash();
      }
      if (r.dose != null) lastDose = r.dose;
    });

    doc.fontSize(7).fillColor(MUTED);
    doc.text(tshVals[0].date, chartX, chartY + chartH + 6);
    doc.text(tshVals[tshVals.length - 1].date, chartX + chartW - 60, chartY + chartH + 6, { width: 60, align: 'right' });
    doc.text(`Reference range: ${REF.tsh[0]}–${REF.tsh[1]} mIU/L (shaded)`, chartX, chartY + chartH + 22);
    doc.text('Dashed amber line = dose change', chartX, chartY + chartH + 34);
  } else {
    doc.fontSize(10).fillColor(MUTED).text('Not enough data to plot a trend yet.', chartX, chartY + chartH / 2);
  }
  footer(doc);

  // ---------- Page 4: Medication adherence ----------
  doc.addPage();
  pageHeader(doc, 'Medication Adherence');

  const byMonth = {};
  doseLogs.forEach((l) => {
    const key = monthKey(l.date);
    if (!byMonth[key]) byMonth[key] = { taken: 0, missed: 0 };
    if (l.taken) byMonth[key].taken += 1;
    else byMonth[key].missed += 1;
  });
  const months = Object.keys(byMonth).sort();

  if (months.length === 0) {
    doc.fontSize(10).fillColor(MUTED).text('No medication logs recorded yet.', 40, doc.y + 10);
  } else {
    let ty = doc.y + 10;
    doc.fontSize(8).fillColor(MUTED);
    doc.text('Month', 40, ty, { width: 120 });
    doc.text('Taken', 160, ty, { width: 80 });
    doc.text('Missed', 240, ty, { width: 80 });
    doc.text('Adherence', 320, ty, { width: 100 });
    ty += 16;
    doc.moveTo(40, ty).lineTo(505, ty).strokeColor('#E2E8F0').stroke();
    ty += 8;

    months.forEach((m) => {
      const { taken, missed } = byMonth[m];
      const total = taken + missed;
      const pct = total ? Math.round((taken / total) * 100) : 0;
      doc.fontSize(9).fillColor(WHITE);
      doc.text(formatMonth(m), 40, ty, { width: 120 });
      doc.text(String(taken), 160, ty, { width: 80 });
      doc.fillColor(missed > 0 ? RED : WHITE).text(String(missed), 240, ty, { width: 80 });
      doc.fillColor(pct >= 90 ? GREEN : pct >= 70 ? AMBER : RED).text(`${pct}%`, 320, ty, { width: 100 });
      ty += 18;
    });

    ty += 16;
    doc.fontSize(11).fillColor(WHITE).text(`Current streak: ${getCurrentStreak(new Date().toISOString().slice(0, 10))} days`, 40, ty);
  }
  footer(doc);

  // ---------- Page 5: Symptom trend ----------
  doc.addPage();
  pageHeader(doc, 'Symptom / Wellness Trend');

  if (wellnessLogs.length === 0) {
    doc.fontSize(10).fillColor(MUTED).text('No wellness check-ins recorded yet.', 40, doc.y + 10);
  } else {
    const counts = { good: 0, okay: 0, bad: 0 };
    wellnessLogs.forEach((w) => { if (counts[w.feeling] != null) counts[w.feeling] += 1; });

    let sy = doc.y + 10;
    doc.fontSize(10).fillColor(WHITE).text(
      `${wellnessLogs.length} check-ins recorded — ${counts.good} good, ${counts.okay} okay, ${counts.bad} not great.`,
      40, sy
    );
    sy += 30;

    doc.fontSize(9).fillColor(MUTED).text('Recent check-ins:', 40, sy);
    sy += 18;
    wellnessLogs.slice(0, 25).forEach((w) => {
      if (sy > doc.page.height - 80) {
        footer(doc);
        doc.addPage();
        pageHeader(doc, 'Symptom / Wellness Trend (continued)');
        sy = doc.y + 10;
      }
      const label = w.feeling === 'good' ? 'Feeling good' : w.feeling === 'okay' ? 'Feeling okay' : 'Not great';
      const color = w.feeling === 'good' ? GREEN : w.feeling === 'okay' ? AMBER : RED;
      doc.fontSize(9).fillColor(MUTED).text(`${w.date} ${w.time || ''}`, 40, sy, { width: 140 });
      doc.fillColor(color).text(label, 180, sy);
      sy += 16;
    });
  }
  footer(doc);

  doc.end();
}

module.exports = { generateDoctorReportPdf };
